# Site
title:              Jiwon Jeong
bio:                "안녕하세요. 멈추지않고 성장하는 개발자 정지원입니다."
description:        "끊임없이 배우며 성장하는 엔지니어"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/post/profile.jpg'
background:         'assets/img/placeholder-big.jpg'
#'assets/img/desktop-white-bg.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url               :  https://traveloving2030.github.io/jiwon
plugins:
  - jekyll-sitemap
repository        : "traveloving2030/jiwon"



# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   jiwon

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              traveloving2030@gmail.com
#twitter:            username
#facebook:           username
github-url:         "traveloving2030"    # https://github.com/ 뒤 주소만 입력
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          "2z__im"   # https://www.instagram.com/
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
